// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SERVWeb {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Content titlePlaceholderContent;
		
		protected System.Web.UI.WebControls.Content contentPlaceholderContent;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtOldPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNewPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNewPassword2;
		
		protected System.Web.UI.WebControls.Button cmdChange;
		
		public new SERVWeb.Master Master {
			get {
				return ((SERVWeb.Master)(base.Master));
			}
		}
	}
}
