// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SERVWeb {
	
	
	public partial class Master {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl titlePlaceholder;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl topControl;
		
		protected System.Web.UI.HtmlControls.HtmlForm cententForm;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl contentPlaceholder;
	}
}
