// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SERVWeb {
	
	
	public partial class RunStats {
		
		protected System.Web.UI.WebControls.Content titlePlaceholderContent;
		
		protected System.Web.UI.WebControls.Content contentPlaceholderContent;
		
		protected System.Web.UI.WebControls.DataGrid dgRunLog;
		
		protected System.Web.UI.WebControls.DataGrid dgTodaysUsers;
		
		protected System.Web.UI.WebControls.DataGrid dgTop10;
		
		protected System.Web.UI.WebControls.DataGrid dgTop102013;
		
		protected System.Web.UI.WebControls.GridView dgHeatMap;
		
		protected System.Web.UI.WebControls.DataGrid dgAvgPerDay;
		
		protected System.Web.UI.WebControls.DataGrid dgReport;
		
		protected System.Web.UI.WebControls.DataGrid dgRunNoLogin;
		
		protected System.Web.UI.WebControls.Label lblRunNoLogin;
		
		public new SERVWeb.Master Master {
			get {
				return ((SERVWeb.Master)(base.Master));
			}
		}
	}
}
